//==========================================================
//  Title     : SONY Mobile CIS
//  Comment   : DUBE block
//  Project   : 
//
//  File Name : 
//
//
//  CONFIDENTIAL AND PROPRIETARY PRODUCT OF SONY CORPORATION
//  Copyright (c) 2015 Sony Corporation.  All Rights Reserved.
//
//  Reference File Name     : (Generated by Excel)
//  Reference File Revision : (none)
//  Reference File Project  : 
//==========================================================



module                  SCL_CIBLK(
     VTCLK
    ,XRST
    ,IHSYNC
    ,IVSYNC
    ,IDATA_EN
    ,SCL_CIBLK_IBLK_H
    ,SCL_CIBLK_IBLK_V
);


/*************************************************
INPUT , OUTPUT
*************************************************/
input           VTCLK;                          // 
input           XRST;                           // 
input           IHSYNC;                         // 
input           IVSYNC;                         // 
input           IDATA_EN;                       // 
output  [9:0]   SCL_CIBLK_IBLK_H;               // 
output  [9:0]   SCL_CIBLK_IBLK_V;               // 

/*************************************************
reg, wire
*************************************************/
reg [9:0] SCL_CIBLK_IBLK_H;
reg [9:0] SCL_CIBLK_IBLK_V_PRE;
wire [9:0] SCL_CIBLK_IBLK_V;

assign SCL_CIBLK_IBLK_V = SCL_CIBLK_IBLK_V_PRE - 2'd2;

always @(posedge VTCLK or negedge XRST) begin
  if (XRST == 1'b0) begin
    SCL_CIBLK_IBLK_H <= 0;
    SCL_CIBLK_IBLK_V_PRE <= 0;
  end else begin
    //calc SCL_CIBLK_IBLK_H
    if (IHSYNC == 1'b1) begin
      SCL_CIBLK_IBLK_H <= 1'b0;
    end else begin
      SCL_CIBLK_IBLK_H <= SCL_CIBLK_IBLK_H + 1'b1;
    end

    //cac SCL_CIBLK_IBLK_V
    if (IVSYNC == 1'b1) begin
      SCL_CIBLK_IBLK_V_PRE <= 1'b0;
    end else if (IHSYNC == 1'b1) begin
      SCL_CIBLK_IBLK_V_PRE <= SCL_CIBLK_IBLK_V_PRE + 1'b1;
    end else begin
      SCL_CIBLK_IBLK_V_PRE <= SCL_CIBLK_IBLK_V_PRE;
    end
  end
end

endmodule
