//==========================================================
//  Title     : SONY Mobile CIS
//  Comment   : DUBE block
//  Project   : 
//
//  File Name : 
//
//
//  CONFIDENTIAL AND PROPRIETARY PRODUCT OF SONY CORPORATION
//  Copyright (c) 2015 Sony Corporation.  All Rights Reserved.
//
//  Reference File Name     : (Generated by Excel)
//  Reference File Revision : (none)
//  Reference File Project  : 
//==========================================================



module                  SCL_CDIST(
     VTCLK
    ,XRST
    ,SCL_COTOI_OTOI_H_1D
    ,SCL_COTOI_OTOI_V_1D
    ,SCL_SEL4BLK_LU_H
    ,SCL_SEL4BLK_LU_V
    ,SCL_CDIST_ALPHA
    ,SCL_CDIST_BETA
);


/*************************************************
INPUT , OUTPUT
*************************************************/
input           VTCLK;                          // 
input           XRST;                           // 
input   [17:0]  SCL_COTOI_OTOI_H_1D;            // 
input   [17:0]  SCL_COTOI_OTOI_V_1D;            // 
input   [9:0]  SCL_SEL4BLK_LU_H;               // 
input   [9:0]  SCL_SEL4BLK_LU_V;               // 
output  [8:0]   SCL_CDIST_ALPHA;                // 
output  [8:0]   SCL_CDIST_BETA;                 // 

/*************************************************
reg, wire
*************************************************/
reg [8:0] SCL_CDIST_ALPHA;
reg [8:0] SCL_CDIST_BETA;
wire [17:0] SCL_CDIST_ALPHA_pre;
wire [17:0] SCL_CDIST_BETA_pre;

assign SCL_CDIST_ALPHA_pre = SCL_COTOI_OTOI_H_1D - {SCL_SEL4BLK_LU_H, 8'b0} + 8'b10000000;
assign SCL_CDIST_BETA_pre = SCL_COTOI_OTOI_V_1D - {SCL_SEL4BLK_LU_V, 8'b0} + 8'b10000000;

always @(posedge VTCLK or negedge XRST) begin

  if (XRST == 1'b0) begin
    SCL_CDIST_ALPHA <= 0;
    SCL_CDIST_BETA <= 0;
  end else begin
    //calc SCL_CDIST_ALPHA
    SCL_CDIST_ALPHA <= SCL_CDIST_ALPHA_pre[8:0];
    //calc SCL_CDIST_BETA
    SCL_CDIST_BETA <= SCL_CDIST_BETA_pre[8:0];
  end

end

endmodule
